### ISSUE TITLE
[Question] Do you use or recommend using any particular JOSM Extensions?

### ISSUE THREAD

**Issue by Codebot2455** [phbender/liblanelet#4]
Do you use or recommend using any particular JOSM Extensions? I'm new to JOSM and would like recommendations for Plugins, Presets, Rules, Styles(besides labelet_style), or Backgrounds that are helpful for autonomous vehicles. Could you please give more details on your configuration?

Thank you very much for the help & also for sharing this incredible project!

**Comment by XiGuaSZ** [comment]
+1，how to quickly design the lanelets?
Thank you very much for the help & also for sharing this incredible project!

**Comment by phbender** [comment]
Hi, sorry for the late reply.

 @bobjohnson2040 We run our own TMS tiles server, and the images are generated with LIDAR or camera sensors. In addition to that, we bought some high accuracy aerial images from local authorities. We did not use other extensions, but I think there is much room for improvements.

@XiGuaSZ There is no particular guideline – we just design, use the map in our simulation and developed a set of tools to check the map. JOSM is not too helpful here since we abuse it a little bit.

**Comment by XiGuaSZ** [comment]
@phbender thanks for your reply.now，you developed tools that  drawed map automatically? this is  cool

**Comment by XiGuaSZ** [comment]
@phbender “Making Bertha Drive — An Autonomous Journey on a Historic Route”, is this paper released by your team? in this paper,after the 3D dense map onto 2D, How do you stack it onto the lanelets?
Thank you very much for the help & also for sharing this incredible project!
